name: ferc-data
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - numpy
  - pandas=0.25.*
  - pip
#   - matplotlib=3.*
  - joblib
  - xlrd
  
  # GIS dependencies from conda-forge in case ppl start using shapefiles
  - conda-forge::fiona
  - conda-forge::geopandas
  - conda-forge::shapely
  - conda-forge::descartes
